
## global vars
title: Ali Raza - Web Developer // Designer
main_heading: Ali Raza
kicker: Web Developer // Designer

## build settings specific to cloud 9 platform
## terminal cmd: jerkyll serve -w
baseurl: ''
sass:
    style: compressed

## conversion
markdown: kramdown
highlighter: rouge
