
## global vars
title: Portfolio Site

## build settings specific to cloud 9 platform
## terminal cmd: jerkyll serve -w
baseurl: ''
sass:
    style: compressed

## conversion
markdown: kramdown
highlighter: rouge
